name       : dnsmasq
version    : 2.73
release    : 4
source     :
    - http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.73.tar.xz : 0bff81103e53fcab3a3c4d0fd6df1882f9446dca4fa74ff8270e1d2ab872d8f6
license    : GPL-2.0
summary    : DNS forwarder
description: |
    DNS forwarder
builddeps  :
    - pkgconfig(nettle)
setup      : |
    # Causes severe delays otherwise
    %patch -p1 < $pkgfiles/no-ping.patch
build      : |
    %make COPTS="-DHAVE_DNSSEC" CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS"
install    : |
    %make_install COPTS="-DHAVE_DNSSEC" PREFIX=/usr BINDIR=/usr/bin
    install -D -m 00644 "dnsmasq.conf.example" $installdir/etc/dnsmasq.conf
    sed -i 's@%%PREFIX%%@/usr@' $installdir/etc/dnsmasq.conf
    install -D -m 00644 trust-anchors.conf $installdir/usr/share/dnsmasq/trust-anchors.conf
